name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # --- TAMBAHKAN BAGIAN INI ---
    environment:
      name: github-pages # Pastikan namanya sesuai dengan nama Environment di Settings kamu
      url: ${{ steps.deployment.outputs.page_url }}
    # ----------------------------
    
    concurrency:
      group: "pages"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

     - name: Inject Secret into HTML
        run: |
          sed -i "s|TOKEN_DARI_GITHUB|${{ secrets.HF_TOKEN }}|g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
