name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

# TAMBAHKAN BAGIAN INI (Sangat Penting)
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    # Izinkan satu deployment dalam satu waktu
    concurrency:
      group: "pages"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Inject Secret into HTML
        run: |
          # Mengganti placeholder dengan Secret asli
          sed -i 's/TOKEN_DARI_GITHUB/${{ secrets.HF_TOKEN }}/g' index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
